name: Publish Docker image
on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    services:
      db: 
        image: docker.pkg.github.com/pichot/territoires.fyi.db/territoires.fyi.db:v0.1
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -q -h db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      -
        name: Run Hasura
        run: |
          docker run -d --net=host -p 8080:8080 \
            -e HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:postgres@localhost:5432/territoires.fyi \
            hasura/graphql-engine:latest
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          tag-match: v(.*)
          images: pichot/territoires.fyi.www
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          allow: |
            network.host
          build-args: |
            SEARCH_URL=${{ secrets.SEARCH_URL }}
            SEARCH_KEY=${{ secrets.SEARCH_KEY }}
            API_URL=http://localhost:8080/v1/graphql
