name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    services:
      db: 
        image: docker.pkg.github.com/pichot/territoires.fyi.db/territoires.fyi.db:v0.1
        env:
          POSTGRES_PASSWORD: postgres
      hasura:
        image: hasura/graphql-engine:latest
        env:
          HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@db:5432/territoires.fyi
          HASURA_GRAPHQL_ENABLE_CONSOLE: true
          HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup,http-log,webhook-log,websocket-log,query-log
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          tag-match: v(.*)
          images: pichot/territoires.fyi.www
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          build-args: |
            SEARCH_URL=${{ secrets.SEARCH_URL }}
            SEARCH_KEY=${{ secrets.SEARCH_KEY }}
            API_URL=http://hasura:8080/graphql/v1
